version: "3.3"
services:
  app:
    build: /home/mkoniuszy/IdeaProjects/jjdd2-mojito

    ports:
      - 8801:8080
    depends_on:
      - db
  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=Data
      - MYSQL_USER=mokoniuszy
      - MYSQL_PASSWORD=admin
    ports:
      - 3306:3306